services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: profile-manager-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:8000